---
server:
  port: 8081
  host: 0.0.0.0
CURRENCY_OUTER_KEY: c4d463b3224d9b77380e7e13
DB:
  host: db
  user: admin
  password: admin
  dbname: currency_db
  port: 5432
  sslmode: disable
  TimeZone: UTC
  Connect_timeout: 10
GRPC:
  port: 50051
  protocol: tcp
auth:
  base_url: http://auth-generator:8080
