apiVersion: 1
datasources:
  - name: Postgres
    type: postgres
    access: proxy
    url: db:5432
    database: currency_db
    user: admin
    secureJsonData:
      password: admin
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    isDefault: true
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
